name: Countinous Integration Workflow

# This work flow will be triggered once a PR is created against the main branch

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
  push:
    branches:
      - main
    paths: 'api/**'

jobs:

  # Run the tests definded under api/tests
  test:
    name: "Run Unit Tests"

    defaults:
      run:
        shell: bash
        working-directory: ./api
    
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
