name: Creating a Development Environment to test Every PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
  
  workflow_dispatch:
    inputs:
      pr_number_input: 
        description: 'Pull Request Number'
        required: true

      
jobs:
  create:
    name: 'Create a Development Env'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get Pull Request Ref 
      uses: actions/github-script@v5
      id: get_pr_ref
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          console.log(${{ github }});
          
          const response = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.inputs.pr_number_input }}
          });
          
          if (response.data.number !== ${{ github.event.inputs.pr_number_input }}) {
            throw new Error('Pull request is not open or number is not valid!');
          }
          console.log("PR ref: " + response.data.head.ref);
          return response.data.head.ref;

