name: Creating a Development Environment to test Every PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
    types:
      - opened
  
  workflow_dispatch:
    inputs:
      pr_number_input: 
        description: 'Pull Request Number'
        required: true

jobs:

  create-dev-env:
    name: "Create a Development Environment"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:

      - name: Get the PR Number
        id: get-pr-number
        uses: actions/github-script@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |

            let pr_number;
            console.log(${{ github.event.pull_request }});
            if ( ${{ github.event.pull_request }} != undefined )
              pr_number = ${{ github.event.pull_request.number }};
            else
              pr_number = ${{ github.event.inputs.pr_number_input }};

            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });

            console.log(pr);

            if(! ${{ github.event.pull_request }} ){
              if(pr.data.number != pr_number)
                throw new Error ("PR does not exist");
            }

            console.log("PR Ref is:" + pr.data.head.ref);
            return pr.data.head.ref;
      
        
      
