name: Creating a Development Environment to test Every PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
  
  workflow_dispatch:
    inputs:
      pr_number_input: 
        description: 'Pull Request Number'
        required: true

      
jobs:
  create:
    name: 'Create a Development Env'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get Pull Request Number 
      uses: actions/github-script@v6
      id: get_pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |

          if (${{ github.event_name }} == 'workflow_dispatch') {
            
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_number_input }}
            });

            if (response.data.number !== ${{ github.event.inputs.pr_number_input }}) {
              throw new Error ("PR number does not exist");
            }
            console.log("PR Ref is:" + response.data.head.ref);
            return response.data.head.ref;

          }

          return ${{ github.ref }}
