name: Creating a Development Environment to test Every PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
  
  workflow_dispatch:
    inputs:
      pr_number_input: 
        description: 'Pull Request Number'
        required: true

      
jobs:
  create:
    name: 'Create a Development Env'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    env: 
      event: ${{ github.event }}
    
    steps:
    
    - name: Get Pull Request Number
      uses: actions/github-script@v5
      id: get_pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let pr_number;

          console.log(1);
          if ( process.env.event.inputs ) {
            pr_number = process.env.event.inputs.pr_number_input
          }
          else {
            pr_number = process.env.event.pull_request.number 
          }

          console.log(2);


          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          console.log(3);


          if( process.env.event.inputs ){
            if(pr.data.number !== pr_number)
              throw new Error ("PR does not exist");
          }
          console.log(4);

          console.log("PR Ref is:" + pr.data.head.ref);
          return pr.data.head.ref;
