name: Creating a Dev Environment per PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

      
jobs:
  create:
    name: 'Create a Development Env'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:


    # checkout to the branch that contains the infra files
    - name: Checkout the Repo to the infra branch
      uses: actions/checkout@v2
      with:
        ref: infra
      
    
    # settup terraform on the runner machine
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.5.5
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
    
    # create a new file from the image saved in infra/development/development_instance.tf.example
    # return the newly created instance file name and the output expected from terraform
    - name: Create Dev Instance Resource File
      id: create-resource-file
      working-directory: infra/development/
      run: |
        chmod +x create_instance_resource.sh
        OUTPUT="$(./create_instance_resource.sh PR_${{ github.event.pull_request.number }} | jq -r .resource_id)"
        ls -l
        echo "RESOURCE_ID=$OUTPUT" >> $GITHUB_OUTPUT
    
    - name: Terraform Init and Validate
      id: terraform-init
      working-directory: infra/development/
      run: |
        terraform init
        terraform validate -no-color
    
    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -no-color
      working-directory: infra/development/

    - name: Terraform Apply
      id: terraform-apply
      working-directory: infra/development/
      run: |
        terraform apply -auto-approve

    - name: Extract Terraform Output
      id: terraform-output
      working-directory: infra/development/
      run: |
        terraform output development_dns_${{ steps.create-resource-file.outputs.RESOURCE_ID }}








